# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbinemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='windfarm',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
