# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbinemanagement', '0003_auto_20170816_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='windturbine',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='windfarm',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
