# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turbinemanagement', '0006_auto_20170818_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windturbine',
            name='name',
        ),
    ]
