# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbinemanagement', '0008_windturbine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='windturbine',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='ipv4'),
        ),
    ]
