# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbinemanagement', '0009_windturbine_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='windturbineerror',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
