# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbinemanagement', '0011_auto_20170828_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='windturbinedata',
            options={'verbose_name_plural': 'Windturbine data'},
        ),
        migrations.AddField(
            model_name='windturbinedata',
            name='brake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='windturbinedata',
            name='wing_angle',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
