# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbinemanagement', '0012_auto_20170828_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='windturbinesetting',
            name='brake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='windturbinesetting',
            name='wing_angle',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
