# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbinemanagement', '0013_auto_20170828_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='windturbine',
            name='api_token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
