# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0002_auto_20170817_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ('timestamp',)},
        ),
    ]
