# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0003_auto_20170823_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='api_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
