# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0004_auto_20170825_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='api_response',
            new_name='result',
        ),
    ]
