# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windturbine_settings', '0003_auto_20170817_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='windturbinesetting',
            old_name='windturbine_id',
            new_name='windturbine',
        ),
    ]
