# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windturbine_settings', '0005_auto_20170824_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windturbinesetting',
            name='wind_speed',
        ),
    ]
