# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sensor_type_data', models.CharField(max_length=255)),
                ('current_value', models.CharField(max_length=255)),
                ('windmill_state', models.IntegerField()),
            ],
        ),
    ]
