# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-16 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WindturbineData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windturbine_id', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(max_length=255)),
                ('temp_gearbox', models.IntegerField(default=0)),
                ('temp_generator', models.IntegerField(default=0)),
                ('rpm_shaft', models.IntegerField(default=0)),
                ('wind_speed', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Windturbine data',
            },
        ),
    ]
