# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windturbine_data', '0004_auto_20170818_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='windturbinedata',
            old_name='windturbine_id',
            new_name='windturbine',
        ),
    ]
