# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windturbine_data', '0005_auto_20170823_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='windturbinedata',
            name='brake',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='windturbinedata',
            name='wing_angle',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
